// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChWrvNDF4ENv0X63Ft_iiGE7ypwpmsFAU',
    appId: '1:793159943944:web:2c704878db8aa1ba4d0ebd',
    messagingSenderId: '793159943944',
    projectId: 'notewiz-mtsi',
    authDomain: 'notewiz-mtsi.firebaseapp.com',
    storageBucket: 'notewiz-mtsi.appspot.com',
    measurementId: 'G-S18K5BQ0JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKcNfEPnK9aW-BUoEgFniJg-NsdnUB-7k',
    appId: '1:793159943944:android:37c4095c77aeccf94d0ebd',
    messagingSenderId: '793159943944',
    projectId: 'notewiz-mtsi',
    storageBucket: 'notewiz-mtsi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXAL8-Qb6YCYMR1eO6_tzLFnTtyOHrBPU',
    appId: '1:793159943944:ios:6972cc8bcf4e306d4d0ebd',
    messagingSenderId: '793159943944',
    projectId: 'notewiz-mtsi',
    storageBucket: 'notewiz-mtsi.appspot.com',
    iosClientId: '793159943944-1t3310an8adjjipq5hlsup34a4slrul1.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteWiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXAL8-Qb6YCYMR1eO6_tzLFnTtyOHrBPU',
    appId: '1:793159943944:ios:0bff51ba1389647e4d0ebd',
    messagingSenderId: '793159943944',
    projectId: 'notewiz-mtsi',
    storageBucket: 'notewiz-mtsi.appspot.com',
    iosClientId: '793159943944-g6tr310a60kn4sc478skhtocn3lo1e2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteWiz.RunnerTests',
  );
}
